version: "2.2"

services:

  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: azure-cosmosdb-linux-emulator
    hostname: "azure-cosmosdb-linux-emulator"
    tty: true
    mem_limit: 12GB
    cpu_count: 8
    networks:
       - poc-be
    ports:
      - 8082:8081
      - 10251:10251
      - 10252:10252
      - 10253:10253
      - 10254:10254
    expose:
      - "8082"
      - "10251-10255"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1

volumes:
  certs:
    driver: local

networks:
  poc-be:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450