name: 'Code Review'

on:
  push:
    branches: ['main']
    paths:
      - apps/**
      - packages/**
      - package.json
  pull_request:
    types: [opened, synchronize]
    paths:
      - src/**
      - package.json
  workflow_dispatch: {}

jobs:
  code_review:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    environment: IntegrationTests
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: 'Code review'
        run: yarn run code-review
      
      - name: Set env
        run: |
          echo "NODE_TLS_REJECT_UNAUTHORIZED=0" >> $GITHUB_ENV
          echo "COSMOSDB_NAME=${{github.run_id}}" >> $GITHUB_ENV
          echo "COSMOSDB_CONNECTION_STRING=${{secrets.COSMOSDB_CONNECTION_STRING}}" >> $GITHUB_ENV
          echo "MONGODB_NAME=${{github.run_id}}" >> $GITHUB_ENV
          echo "MESSAGEQUEUE_TOPIC=integration-topic" >> $GITHUB_ENV

      - name: Stop containers if up 
        run: |
          docker-compose -f "__integrations__/docker-compose.yml" stop
          docker-compose -f "__integrations__/docker-compose.yml" down
          # docker system prune -a -f
      
      - name: Start containers
        run: docker-compose -f "__integrations__/docker-compose.yml" up -d

      - name: Sleep
        run: sleep 30s

      - name: System tests
        run: |
          cd __integrations__
          yarn install --immutable
          yarn test

      - name: Stop containers
        run: |
          docker-compose -f "__integrations__/docker-compose.yml" stop
          docker-compose -f "__integrations__/docker-compose.yml" down
          # docker system prune -a -f

      