name: 'Code Review'

on:
  push:
    branches: ['main']
    paths:
      - apps/**
      - packages/**
      - package.json
  pull_request:
    types: [opened, synchronize]
    paths:
      - src/**
      - package.json
  workflow_dispatch: {}

jobs:
  code_review:
    timeout-minutes: 10
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c #v3.6.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
            
      - name: Start Azure Cosmos DB emulator
        run: >-
          Write-Host "Launching Cosmos DB Emulator"
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          Start-CosmosDbEmulator

      - name: Install dependencies
        run: yarn install --immutable

      - name: Cache turbo build setup
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 #v3.3.1
        with:
          path: node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: 'Code review'
        run: yarn run code-review

      - name: Set env
        run: echo "NODE_TLS_REJECT_UNAUTHORIZED=0" >> $GITHUB_ENV

      - name: Integration test
        run: |
          cd __integrations__
          yarn install --immutable
          docker logs azure-cosmosdb-emulator
          nc -zv 0.0.0.0 8081 || true
          yarn test
          cd ..
        