name: 'Code Review'

on:
  push:
    branches: ['main']
    paths:
      - apps/**
      - packages/**
      - package.json
  pull_request:
    types: [opened, synchronize]
    paths:
      - src/**
      - package.json
  workflow_dispatch: {}

jobs:
#   start_cosmosdb_emulator:
#     timeout-minutes: 10
#     runs-on: windows-latest
#     steps:
#       - name: Start Azure Cosmos DB emulator
#         run: |
#           Write-Host "Launching Cosmos DB Emulator"
#           Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
#           Start-CosmosDbEmulator  
  code_review:
    #needs: start_cosmosdb_emulator
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c #v3.6.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Cache turbo build setup
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 #v3.3.1
        with:
          path: node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: 'Code review'
        run: yarn run code-review

      - name: Set env
        run: echo "NODE_TLS_REJECT_UNAUTHORIZED=0" >> $GITHUB_ENV

      - name: Start cosmosdb
        run: |
          ipaddr="`ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | head -n 1`"
          ifconfig | grep "inet " | grep -Fv 127.0.0.1
          docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
          docker run -p 8081:8081 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254 -m 4g --cpus=2.0 --name=test-linux-emulator  -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false -e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=$ipaddr -d -it mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
          sleep 30
          nc -zv 0.0.0.0 8081 || true
          nc -zv $ipaddr 8081 || true
          # curl -k https://localhost:8081/_explorer/emulator.pem > /tmp/emulatorcert.crt
          # keytool -cacerts -storepass changeit -noprompt -importcert -alias emulator_cert -file /tmp/emulatorcert.crt
        shell: bash

      - name: Integration test
        run: |
          cd __integrations__
          yarn install --immutable
          nc -zv 0.0.0.0 8081 || true
          yarn test
          cd ..  